from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

calc = InlineKeyboardButton('=', callback_data='=')
clear = InlineKeyboardButton('C', callback_data='C')
delete = InlineKeyboardButton('<=', callback_data='<=')
dot = InlineKeyboardButton('.', callback_data='.')
coma = InlineKeyboardButton(',', callback_data=',')
one = InlineKeyboardButton('1', callback_data='1')
two = InlineKeyboardButton('2', callback_data='2')
tree = InlineKeyboardButton('3', callback_data='3')
four = InlineKeyboardButton('4', callback_data='4')
five = InlineKeyboardButton('5', callback_data='5')
six = InlineKeyboardButton('6', callback_data='6')
seven = InlineKeyboardButton('7', callback_data='7')
eight = InlineKeyboardButton('8', callback_data='8')
nine = InlineKeyboardButton('9', callback_data='9')
zero = InlineKeyboardButton('0', callback_data='0')
plus = InlineKeyboardButton('+', callback_data='+')
minus = InlineKeyboardButton('-', callback_data='-')
dev = InlineKeyboardButton('/', callback_data='/')
mult = InlineKeyboardButton('*', callback_data='*')
left = InlineKeyboardButton('(', callback_data='(')
right = InlineKeyboardButton(')', callback_data=')')
sin = InlineKeyboardButton('sin', callback_data='sin(')
cos = InlineKeyboardButton('cos', callback_data='cos(')
pow = InlineKeyboardButton('^', callback_data='**')
sqrt = InlineKeyboardButton('sqrt', callback_data='sqrt(')
complex = InlineKeyboardButton('complex', callback_data='complex(')

calculus = InlineKeyboardMarkup()

calculus.row(one, two, tree, plus, pow)
calculus.row(four, five, six, minus, sqrt)
calculus.row(seven, eight, nine, dev, sin)
calculus.row(left, zero, right, mult, cos)
calculus.row(clear, dot, delete, calc)
calculus.row(complex, coma)
